### ISSUE TITLE
One of the Join Order Benchmark queries stops reducing cardinality error

### ISSUE THREAD

**Issue by JimFAmazon** [postgrespro/aqo#11]
In one case (and one case only), cardinality error achieves stability without progressing towards 0.  here is the query and the plan after convergence.  I also have the states of the aqo tables which I can forward if requested.

Here is one line of the explain output showing a non-converged estimated vs actual rows:

Hash Join  (cost=96459.24..130001.90 rows=68198 width=29) (actual time=973.541..1415.390 rows=198750 loops=3)

The query:

EXPLAIN (analyze,verbose,buffers) SELECT MIN(chn.name) AS character, MIN(t.title) AS movie_with_american_producer FROM char_name AS chn, cast_info AS ci, company_name AS cn, company_type AS ct, movie_companies AS mc, role_type AS rt, title AS t WHERE ci.note  like '%(producer)%' AND cn.country_code  = '[us]' AND t.production_year > 1990 AND t.id = mc.movie_id AND t.id = ci.movie_id AND ci.movie_id = mc.movie_id AND chn.id = ci.person_role_id AND rt.id = ci.role_id AND cn.id = mc.company_id AND ct.id = mc.company_type_id;

The text format plan:

QUERY PLAN
Finalize Aggregate  (cost=242898.15..242898.16 rows=1 width=64) (actual time=6689.777..6689.777 rows=1 loops=1)
  Output: min(chn.name), min(t.title)
  Buffers: shared hit=23037955
  ->  Gather  (cost=242897.93..242898.14 rows=2 width=64) (actual time=6689.740..6689.811 rows=3 loops=1)
        Output: (PARTIAL min(chn.name)), (PARTIAL min(t.title))
        Workers Planned: 2
        Workers Launched: 2
        Buffers: shared hit=23037955
        ->  Partial Aggregate  (cost=241897.93..241897.94 rows=1 width=64) (actual time=6670.368..6670.368 rows=1 loops=3)
              Output: PARTIAL min(chn.name), PARTIAL min(t.title)
              Buffers: shared hit=23037955
              Worker 0: actual time=6663.069..6663.069 rows=1 loops=1
                Buffers: shared hit=7855588
              Worker 1: actual time=6658.810..6658.810 rows=1 loops=1
                Buffers: shared hit=7632929
              ->  Nested Loop  (cost=96460.50..241897.93 rows=1 width=33) (actual time=2452.152..6670.319 rows=3 loops=3)
                    Output: chn.name, t.title
                    Inner Unique: true
                    Buffers: shared hit=23037955
                    Worker 0: actual time=2371.185..6663.041 rows=2 loops=1
                      Buffers: shared hit=7855588
                    Worker 1: actual time=2539.235..6658.735 rows=4 loops=1
                      Buffers: shared hit=7632929
                    ->  Nested Loop  (cost=96460.36..241897.77 rows=1 width=37) (actual time=2452.140..6670.293 rows=3 loops=3)
                          Output: chn.name, ci.role_id, t.title
                          Inner Unique: true
                          Buffers: shared hit=23037933
                          Worker 0: actual time=2371.169..6663.020 rows=2 loops=1
                            Buffers: shared hit=7855583
                          Worker 1: actual time=2539.220..6658.703 rows=4 loops=1
                            Buffers: shared hit=7632920
                          ->  Nested Loop  (cost=96460.23..241897.62 rows=1 width=41) (actual time=2452.113..6670.247 rows=3 loops=3)
                                Output: chn.name, ci.role_id, mc.company_type_id, t.title
                                Inner Unique: true
                                Buffers: shared hit=23037911
                                Worker 0: actual time=2371.132..6662.976 rows=2 loops=1
                                  Buffers: shared hit=7855578
                                Worker 1: actual time=2539.188..6658.652 rows=4 loops=1
                                  Buffers: shared hit=7632911
                                ->  Nested Loop  (cost=96459.80..199048.11 rows=89456 width=29) (actual time=973.601..6596.097 rows=260701 loops=3)
                                      Output: ci.person_role_id, ci.role_id, mc.company_type_id, t.title
                                      Join Filter: (t.id = ci.movie_id)
                                      Buffers: shared hit=23037869
                                      Worker 0: actual time=968.453..6589.125 rows=263841 loops=1
                                        Buffers: shared hit=7855569
                                      Worker 1: actual time=976.696..6582.546 rows=264690 loops=1
                                        Buffers: shared hit=7632894
                                      ->  Hash Join  (cost=96459.24..130001.90 rows=68198 width=29) (actual time=973.541..1415.390 rows=198750 loops=3)
                                            Output: mc.movie_id, mc.company_type_id, t.title, t.id
                                            Inner Unique: true
                                            Hash Cond: (mc.movie_id = t.id)
                                            Buffers: shared hit=270485
                                            Worker 0: actual time=968.404..1435.629 rows=203090 loops=1
                                              Buffers: shared hit=90069
                                            Worker 1: actual time=976.625..1420.650 rows=197823 loops=1
                                              Buffers: shared hit=90479
                                            ->  Hash Join  (cost=6990.11..39505.27 rows=391430 width=8) (actual time=49.950..343.319 rows=384599 loops=3)
                                                  Output: mc.movie_id, mc.company_type_id
                                                  Inner Unique: true
                                                  Hash Cond: (mc.company_id = cn.id)
                                                  Buffers: shared hit=54971
                                                  Worker 0: actual time=49.496..350.360 rows=393049 loops=1
                                                    Buffers: shared hit=18231
                                                  Worker 1: actual time=49.708..348.897 rows=389949 loops=1
                                                    Buffers: shared hit=18641
                                                  ->  Parallel Seq Scan on public.movie_companies mc  (cost=0.00..29661.37 rows=1087137 width=12) (actual time=0.143..82.673 rows=869710 loop
s=3)
                                                        Output: mc.id, mc.movie_id, mc.company_id, mc.company_type_id, mc.note
                                                        Buffers: shared hit=37478
                                                        Worker 0: actual time=0.111..81.862 rows=860027 loops=1
                                                          Buffers: shared hit=12390
                                                        Worker 1: actual time=0.136..85.262 rows=892083 loops=1
                                                          Buffers: shared hit=12800
                                                  ->  Hash  (cost=5932.46..5932.46 rows=84612 width=4) (actual time=49.380..49.380 rows=84843 loops=3)
                                                        Output: cn.id
                                                        Buckets: 131072  Batches: 1  Memory Usage: 4007kB
                                                        Buffers: shared hit=17433
                                                        Worker 0: actual time=48.959..48.959 rows=84843 loops=1
                                                          Buffers: shared hit=5811
                                                        Worker 1: actual time=49.206..49.206 rows=84843 loops=1
                                                          Buffers: shared hit=5811
                                                        ->  Seq Scan on public.company_name cn  (cost=0.00..5932.46 rows=84612 width=4) (actual time=0.110..35.890 rows=84843 loops=3)
                                                              Output: cn.id
                                                              Filter: ((cn.country_code)::text = '[us]'::text)
                                                              Rows Removed by Filter: 150154
                                                              Buffers: shared hit=17433
                                                              Worker 0: actual time=0.058..35.900 rows=84843 loops=1
                                                                Buffers: shared hit=5811
                                                              Worker 1: actual time=0.126..35.363 rows=84843 loops=1
                                                                Buffers: shared hit=5811
                                            ->  Hash  (cost=67601.90..67601.90 rows=1749378 width=21) (actual time=914.259..914.259 rows=1749032 loops=3)
                                                  Output: t.title, t.id
                                                  Buckets: 2097152  Batches: 1  Memory Usage: 110019kB
                                                  Buffers: shared hit=215514
                                                  Worker 0: actual time=909.719..909.719 rows=1749032 loops=1
                                                    Buffers: shared hit=71838
                                                  Worker 1: actual time=917.516..917.516 rows=1749032 loops=1
                                                    Buffers: shared hit=71838
                                                  ->  Seq Scan on public.title t  (cost=0.00..67601.90 rows=1749378 width=21) (actual time=0.099..446.134 rows=1749032 loops=3)
                                                        Output: t.title, t.id
                                                        Filter: (t.production_year > 1990)
                                                        Rows Removed by Filter: 779280
                                                        Buffers: shared hit=215514
                                                        Worker 0: actual time=0.117..418.654 rows=1749032 loops=1
                                                          Buffers: shared hit=71838
                                                        Worker 1: actual time=0.059..457.994 rows=1749032 loops=1
                                                          Buffers: shared hit=71838
                                      ->  Index Scan using movie_id_cast_info on public.cast_info ci  (cost=0.56..1.00 rows=1 width=12) (actual time=0.015..0.026 rows=1 loops=596250)
                                            Output: ci.id, ci.person_id, ci.movie_id, ci.person_role_id, ci.note, ci.nr_order, ci.role_id
                                            Index Cond: (ci.movie_id = mc.movie_id)
                                            Filter: (ci.note ~~ '%(producer)%'::text)
                                            Rows Removed by Filter: 34
                                            Buffers: shared hit=22767384
                                            Worker 0: actual time=0.015..0.025 rows=1 loops=203090
                                              Buffers: shared hit=7765500
                                            Worker 1: actual time=0.015..0.026 rows=1 loops=197823
                                              Buffers: shared hit=7542415
                                ->  Index Scan using char_name_pkey on public.char_name chn  (cost=0.43..0.48 rows=1 width=20) (actual time=0.000..0.000 rows=0 loops=782104)
                                      Output: chn.id, chn.name, chn.imdb_index, chn.imdb_id, chn.name_pcode_nf, chn.surname_pcode, chn.md5sum
                                      Index Cond: (chn.id = ci.person_role_id)
                                      Buffers: shared hit=42
                                      Worker 0: actual time=0.000..0.000 rows=0 loops=263841
                                        Buffers: shared hit=9
                                      Worker 1: actual time=0.000..0.000 rows=0 loops=264690
                                        Buffers: shared hit=17
                          ->  Index Only Scan using company_type_pkey on public.company_type ct  (cost=0.13..0.15 rows=1 width=4) (actual time=0.010..0.010 rows=1 loops=10)
                                Output: ct.id
                                Index Cond: (ct.id = mc.company_type_id)
                                Heap Fetches: 4
                                Buffers: shared hit=22
                                Worker 0: actual time=0.019..0.019 rows=1 loops=2
                                  Buffers: shared hit=5
                                Worker 1: actual time=0.010..0.010 rows=1 loops=4
                                  Buffers: shared hit=9
                    ->  Index Only Scan using role_type_pkey on public.role_type rt  (cost=0.14..0.15 rows=1 width=4) (actual time=0.006..0.006 rows=1 loops=10)
                          Output: rt.id
                          Index Cond: (rt.id = ci.role_id)
                          Heap Fetches: 4
                          Buffers: shared hit=22
                          Worker 0: actual time=0.008..0.008 rows=1 loops=2
                            Buffers: shared hit=5
                          Worker 1: actual time=0.006..0.006 rows=1 loops=4
                            Buffers: shared hit=9
Planning time: 11.438 ms
Execution time: 6698.929 ms
Plan Hash: -1203362165
Using aqo: true
(146 rows)

**Comment by danolivo** [comment]
Thank you for the notice. Many of issues like this  is a problem of PostgreSQL optimizer. However I will study this case.

**Comment by danolivo** [comment]
The problem has been solved
