### ISSUE TITLE
ERROR:  could not find block containing chunk

### ISSUE THREAD

**Issue by JimFAmazon** [postgrespro/aqo#12]
The error above is raised when attempting to EXPLAIN ANALYZE a statement (shown below) that is being managed by aqo.  If aqo.mode is set to 'disabled', then the error no longer appears and the EXPLAIN ANALYZE completes successfully.  If aqo.mode is subsequently reset, the error reappears.  This is currently reproducible.

In case there is some sort of interaction here, I'll mention that pg_stat_statements and apg_plan_mgmt were also overriding the ExecutorEnd hook in this test, with shared_preload_libraries listing them in the order pg_stat_statements,aqo,apg_plan_mgmt.

imdbload=# EXPLAIN (ANALYZE) SELECT MIN(n.name) AS member_in_charnamed_movie FROM cast_info AS ci, company_name AS cn, keyword AS k, movie_companies AS mc, movie_keyword AS mk, name AS n, title AS t WHERE k.keyword ='character-name-in-title' AND n.name  LIKE '%Bert%' AND n.id = ci.person_id AND ci.movie_id = t.id AND t.id = mk.movie_id AND mk.keyword_id = k.id AND t.id = mc.movie_id AND mc.company_id = cn.id AND ci.movie_id = mc.movie_id AND ci.movie_id = mk.movie_id AND mc.movie_id = mk.movie_id;
ERROR:  could not find block containing chunk 0x2b625af3cd80
imdbload=# set aqo.mode = 'disable';
ERROR:  invalid value for parameter "aqo.mode": "disable"
HINT:  Available values: intelligent, forced, controlled, learn, disabled.
imdbload=# set aqo.mode = 'disabled';
SET
imdbload=# EXPLAIN (ANALYZE) SELECT MIN(n.name) AS member_in_charnamed_movie FROM cast_info AS ci, company_name AS cn, keyword AS k, movie_companies AS mc, movie_keyword AS mk, name AS n, title AS t WHERE k.keyword ='character-name-in-title' AND n.name  LIKE '%Bert%' AND n.id = ci.person_id AND ci.movie_id = t.id AND t.id = mk.movie_id AND mk.keyword_id = k.id AND t.id = mc.movie_id AND mc.company_id = cn.id AND ci.movie_id = mc.movie_id AND ci.movie_id = mk.movie_id AND mc.movie_id = mk.movie_id;
QUERY PLAN
Aggregate  (cost=2938.32..2938.33 rows=1 width=32) (actual time=4747.865..4747.865 rows=1 loops=1)
  ->  Nested Loop  (cost=2.71..2938.31 rows=1 width=15) (actual time=26.390..4744.284 rows=11538 loops=1)
        ->  Nested Loop  (cost=2.28..2937.87 rows=1 width=27) (actual time=26.380..4718.974 rows=11538 loops=1)
              ->  Nested Loop  (cost=1.86..2937.43 rows=1 width=31) (actual time=26.365..4683.451 rows=11538 loops=1)
                    ->  Nested Loop  (cost=1.43..2936.94 rows=1 width=23) (actual time=26.357..4668.745 rows=1972 loops=1)
                          ->  Nested Loop  (cost=1.00..2698.36 rows=528 width=12) (actual time=0.653..1276.244 rows=1038393 loops=1)
                                ->  Nested Loop  (cost=0.43..2662.48 rows=34 width=4) (actual time=0.644..39.356 rows=41840 loops=1)
                                      ->  Seq Scan on keyword k  (cost=0.00..2626.12 rows=1 width=4) (actual time=0.628..10.811 rows=1 loops=1)
                                            Filter: (keyword = 'character-name-in-title'::text)
                                            Rows Removed by Filter: 134169
                                      ->  Index Scan using keyword_id_movie_keyword on movie_keyword mk  (cost=0.43..36.02 rows=34 width=8) (actual time=0.012..22.448 rows=41840 loops=1)
                                            Index Cond: (keyword_id = k.id)
                                ->  Index Scan using movie_id_cast_info on cast_info ci  (cost=0.56..0.91 rows=15 width=8) (actual time=0.004..0.026 rows=25 loops=41840)
                                      Index Cond: (movie_id = mk.movie_id)
                          ->  Index Scan using name_pkey on name n  (cost=0.43..0.45 rows=1 width=19) (actual time=0.003..0.003 rows=0 loops=1038393)
                                Index Cond: (id = ci.person_id)
                                Filter: (name ~~ '%Bert%'::text)
                                Rows Removed by Filter: 1
                    ->  Index Scan using movie_id_movie_companies on movie_companies mc  (cost=0.43..0.47 rows=2 width=8) (actual time=0.004..0.006 rows=6 loops=1972)
                          Index Cond: (movie_id = ci.movie_id)
              ->  Index Only Scan using company_name_pkey on company_name cn  (cost=0.42..0.44 rows=1 width=4) (actual time=0.003..0.003 rows=1 loops=11538)
                    Index Cond: (id = mc.company_id)
                    Heap Fetches: 11538
        ->  Index Only Scan using title_pkey on title t  (cost=0.43..0.45 rows=1 width=4) (actual time=0.002..0.002 rows=1 loops=11538)
              Index Cond: (id = ci.movie_id)
              Heap Fetches: 11538
Planning time: 6.762 ms
Execution time: 4747.965 ms
(28 rows)
imdbload=#

**Comment by JimFAmazon** [comment]
I did several other experiments, including removing some or all other extensions from shared_preload_libraries.  Even if aqo is the only extension loaded, the same symptom appears, and then will disappear if aqo.mode is set to 'disabled'.

The instance is running and I can gather additional information if you tell me what you need.  I will be leaving on Jan 31st for a month, though.

**Comment by danolivo** [comment]
AQO repository contains `review_regress_fix` branch. This branch contains many fixes. Now it is most 'hot' branch. I will merge it into `master` after some review, benchmarking and testing.
May be you can do quick check of your queries with this version of aqo?

**Comment by danolivo** [comment]
I fixed this problem. It caused by the nodes without selectivities. Please, verify the test.
