### ISSUE TITLE
Recommended way to delete queries

### ISSUE THREAD

**Issue by JimFAmazon** [postgrespro/aqo#5]
What is the recommended way to delete queries that a user doesn't want to track any more?  Do you recommend just deleting unwanted rows from aqo_query_texts and aqo_queries, or is there an API for that?

**Comment by JimFAmazon** [comment]
I see that the DDL has DELETE CASCADE specified, so it looks like the idea is to have users understand the schema and delete the rows and let referential actions handle it.  This certainly works but a non-expert user could delete the dependent row and mess things up.

**Comment by danolivo** [comment]
Now we have set of service functions to enable, disable, drop query from the AQO knowledge base.
