### ISSUE TITLE
Search path order could cause aqo_* tables to not be stored in the public schema

### ISSUE THREAD

**Issue by JimFAmazon** [postgrespro/aqo#6]
The aqo--1.0.sql file doesn't specify the public schema name on the aqo_* relations, but internally the code expects that these objects will be in the public schema.  Specifying "public." on the aqo_* objects would eliminate this source of errors if the user sets the search_path to pg_catalog, public; (for example).

**Comment by danolivo** [comment]
Thank You for this bug detection. We will fix it soon.

**Comment by danolivo** [comment]
Done
