### ISSUE TITLE
WARNING: Unexpected number of features for hash

### ISSUE THREAD

**Issue by JimFAmazon** [postgrespro/aqo#8]
The following warnings were issued while explain-analyzing the query shown below from the Join Order Benchmark.  This also caused postgres to crash.  I'll delete data and re-try

imdbload=# explain (hashes, verbose, analyze, buffers) SELECT MIN(n.name) AS voicing_actress, MIN(t.title) AS jap_engl_voiced_movie FROM aka_name AS an, char_name AS chn, cast_info AS ci, company_name AS cn, info_type AS it, movie_companies AS mc, movie_info AS mi, name AS n, role_type AS rt, title AS t WHERE ci.note  in ('(voice)', '(voice: Japanese version)', '(voice) (uncredited)', '(voice: English version)') AND cn.country_code ='[us]' AND it.info  = 'release dates' AND n.gender ='f' AND rt.role ='actress' AND t.production_year  > 2000 AND t.id = mi.movie_id AND t.id = mc.movie_id AND t.id = ci.movie_id AND mc.movie_id = ci.movie_id AND mc.movie_id = mi.movie_id AND mi.movie_id = ci.movie_id AND cn.id = mc.company_id AND it.id = mi.info_type_id AND n.id = ci.person_id AND rt.id = ci.role_id AND n.id = an.person_id AND ci.person_id = an.person_id AND chn.id = ci.person_role_id;
WARNING:  unexpected number of features for hash (-101880755, -778540527):						   expected 0 features, obtained 8
WARNING:  unexpected number of features for hash (-101880755, -1173058144):						   expected 7 features, obtained 6
WARNING:  unexpected number of features for hash (-101880755, 1726969303):						   expected 9 features, obtained 8
WARNING:  unexpected number of features for hash (-101880755, 1200086649):						   expected 8 features, obtained 6

**Comment by danolivo** [comment]
Current version in the `review_regress_fix` branch is heavily refined. You can check existence of the problem . If the problem is exist yet you could send me more info and db sample if it possible .

**Comment by danolivo** [comment]
After refactoring (see master branch) I don't watch this warning at all. Please verify your test case. But I want to study the problem more deeply. May you give me the commit number of your aqo version?
